fieldLayouts:
  2796802a-379d-4bc1-af4d-a221d4ef3317:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 15a3b044-3201-461b-a6c8-83f3096500e7
            warning: null
            width: 100
        name: Content
        sortOrder: 1
        uid: 81f0b5de-7856-43f6-bde7-814552024f63
handle: default
name: Default
