fieldLayouts:
  07f1355f-8c03-4d73-9dd8-eddafbaaef20:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 14e892fc-970f-4051-b794-3b0034ce3582
            warning: null
            width: 100
          -
            fieldUid: 496d2b10-36b1-43fb-b114-c61c558b9c57 # Full Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ab9acf9-348a-4014-9bf9-f47f641db264
            warning: null
            width: 100
          -
            fieldUid: 8c14763b-6183-46a0-be68-963de453e209 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc026a2b-0a68-4458-911a-4921c684cfe5
            warning: null
            width: 100
        name: Content
        sortOrder: 1
        uid: bbea7bea-1e05-415a-a114-7d101e583b65
handle: digitalArenaProjects
name: 'Digital Arena Projects'
