fieldLayouts:
  2d982b76-bc21-48d3-a592-6d2ff49ca475:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 550f81ad-6473-4ab8-8e28-06f9e1966aa2
            warning: null
            width: 100
          -
            fieldUid: 8c14763b-6183-46a0-be68-963de453e209 # Description
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a6ee1b3-a714-4ec3-8007-47ce09f0e1e0
            warning: null
            width: 100
        name: Content
        sortOrder: 1
        uid: b2a6dfe9-d9f4-41cc-9452-45333f8e838d
handle: testtags
name: Test
