fieldLayouts:
  3a2d1a05-53a7-4bcf-975f-db73cc851704:
    tabs:
      -
        elements:
          -
            fieldUid: b8829325-5023-46d1-b8a7-03d6dc33525b # Description
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8aa2abc4-f047-4974-aaf9-9c8ac3de258e
            warning: null
            width: 100
          -
            fieldUid: 64644874-c3eb-45b1-bef6-5d51b056c516 # Facebook
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 075ebe7a-ecbf-4ac9-bdb1-056cc4f4aa2e
            warning: null
            width: 100
          -
            fieldUid: 20aece2a-ee02-4c26-b0ad-5006ad525667 # Instagram
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: afed0605-a951-4422-8b3b-8f92810972c1
            warning: null
            width: 100
          -
            fieldUid: a2b3d641-b542-4391-a1f7-26d081db16c6 # Twitter
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a8983f5-a80e-4d73-9922-1e0c7c81f1bb
            warning: null
            width: 100
          -
            fieldUid: e80f79d5-8bfd-403b-8703-cd18785dc47c # Related links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5266dae8-1f98-4f4f-9801-3254b0035fec
            warning: null
            width: 100
        name: Innhold
        sortOrder: 1
        uid: 4c8225a9-795d-47ee-8a2c-94563eabea08
handle: globalInfo
name: 'Global Information'
sortOrder: 2
