contentColumnType: string
fieldGroup: 9e233a7f-8f79-4de8-9450-ffd21b8baeb6
handle: newsMediaPosition
instructions: 'Select the media (image / video) position for the first news item: over the news or flowed to the left.'
name: 'Media position'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Left
        -
          - value
          - left
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Center
        -
          - value
          - center
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
