contentColumnType: text
fieldGroup: 645faae0-b1e8-4ac9-b604-b802d4ca8b4c
handle: openingTimes
instructions: ''
name: 'Opening Times'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
