contentColumnType: string
fieldGroup: 3626e6f0-4597-4098-b20a-fb662ff583a7
handle: relatedLinks
instructions: ''
name: 'Related links'
searchable: true
settings:
  contentTable: '{{%matrixcontent_relatedlinks}}'
  maxBlocks: null
  minBlocks: null
  propagationMethod: none
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
