contentColumnType: text
fieldGroup: 7f4be85f-cd38-42ea-afed-25ab3fd2648e
handle: socialInstagram
instructions: 'Add full url'
name: Instagram
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
