contentColumnType: text
fieldGroup: e1c561c4-1d4c-4087-8ea9-ef82839fa7bd
handle: ticketDescription
instructions: ''
name: 'Ticket Description'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
