contentColumnType: text
fieldGroup: e1c561c4-1d4c-4087-8ea9-ef82839fa7bd
handle: ticketLink
instructions: ''
name: 'Ticket Link'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
