contentColumnType: string
fieldGroup: e1c561c4-1d4c-4087-8ea9-ef82839fa7bd
handle: tickets
instructions: ''
name: Tickets
searchable: true
settings:
  contentTable: '{{%matrixcontent_tickets}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
