field: 62db04ec-3204-4ab4-8ecc-ef980ab2e2e2
fieldLayouts:
  8638ebcb-c4af-4baa-b072-fe1c6ee09cd7:
    tabs:
      -
        elements:
          -
            fieldUid: 3184fc24-35eb-4b0f-b6e1-a3d83399e1ac
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 06177583-2913-430d-b1c6-29172e43a635
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b15b6daa-1c06-42ce-868e-9077af068a7a
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: faa04196-2eb1-4133-9eb1-c0ef74f73686
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  06177583-2913-430d-b1c6-29172e43a635:
    contentColumnType: datetime
    fieldGroup: null
    handle: startTime
    instructions: ''
    name: 'Start Time'
    searchable: true
    settings:
      max: null
      min: null
      minuteIncrement: '30'
      showDate: 0
      showTime: 1
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
  3184fc24-35eb-4b0f-b6e1-a3d83399e1ac:
    contentColumnType: datetime
    fieldGroup: null
    handle: date
    instructions: ''
    name: Date
    searchable: true
    settings:
      max: null
      min: null
      minuteIncrement: '30'
      showDate: 1
      showTime: 0
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
  b15b6daa-1c06-42ce-868e-9077af068a7a:
    contentColumnType: datetime
    fieldGroup: null
    handle: endTime
    instructions: ''
    name: 'End Time'
    searchable: true
    settings:
      max: null
      min: null
      minuteIncrement: '30'
      showDate: 0
      showTime: 1
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
  faa04196-2eb1-4133-9eb1-c0ef74f73686:
    contentColumnType: text
    fieldGroup: null
    handle: ticketInformation
    instructions: ''
    name: 'Ticket Information'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: day
name: Day
sortOrder: 1
