field: 000db67a-24a2-4bcf-9791-76def17c6393
fieldLayouts:
  b0b6f953-e90f-4426-873b-45387e1fbed2:
    tabs:
      -
        elements:
          -
            fieldUid: 2b1efdcb-9276-4409-9c64-eff8299eb6b5
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdd8c1f6-1165-4eec-a7b8-3c1136ee8918
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eed32295-3672-48ed-940e-b593e2257cf4
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2b1efdcb-9276-4409-9c64-eff8299eb6b5:
    contentColumnType: text
    fieldGroup: null
    handle: sectionTitle
    instructions: ''
    name: 'Festival section title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: Festival
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  eed32295-3672-48ed-940e-b593e2257cf4:
    contentColumnType: boolean
    fieldGroup: null
    handle: isProgramVisible
    instructions: ''
    name: 'Show festival program'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  fdd8c1f6-1165-4eec-a7b8-3c1136ee8918:
    contentColumnType: string
    fieldGroup: null
    handle: festivalEntry
    instructions: ''
    name: 'Festival entry'
    searchable: true
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Select festival entry'
      showSiteMenu: true
      source: null
      sources:
        - 'section:301645ea-e60b-4a0b-bb67-58f74bdbca11'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: festival
name: Festival
sortOrder: 2
