field: e80f79d5-8bfd-403b-8703-cd18785dc47c
fieldLayouts:
  f939e842-4d11-4c43-9932-1725df5f3440:
    tabs:
      -
        elements:
          -
            fieldUid: 1ece1b63-6a8c-4ff9-8508-9d49f2215a06
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c1095f5c-a9ea-4d2e-a9df-89ba5530d3d7
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1ece1b63-6a8c-4ff9-8508-9d49f2215a06:
    contentColumnType: text
    fieldGroup: null
    handle: linkTitle
    instructions: ''
    name: 'Link title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  c1095f5c-a9ea-4d2e-a9df-89ba5530d3d7:
    contentColumnType: text
    fieldGroup: null
    handle: linkUrl
    instructions: 'Full link. Include "http://" in front of the link if it''s missing.'
    name: 'Link url'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: link
name: Link
sortOrder: 1
