#!/usr/bin/env bash
# Runs on the VM (sudo). Writes:
#   /srv/ekko/cms.env   — Craft .env (bind-mounted into php container at /var/www/cms/.env)
#   /srv/ekko/.env.gcp  — Compose env: EKKO_PHP_IMAGE / EKKO_NGINX_IMAGE / EKKO_CLOUDSQL_CONNECTION / HTTP_PORT
#
# Pulls DB_PASSWORD from Secret Manager via the VM's own service account.
# Reads /etc/ekko-craft.env (provisioned by Terraform startup script) for the
# Cloud SQL connection name, DB user, DB name, and project.
set -euo pipefail

STACK_DIR="${STACK_DIR:-/srv/ekko}"
PRIMARY_URL="${PRIMARY_SITE_URL:-}"
ENVIRONMENT="${CRAFT_ENVIRONMENT:-staging}"
SECURITY_KEY="${CRAFT_SECURITY_KEY:-}"
PHP_IMAGE="${EKKO_PHP_IMAGE:-}"
NGINX_IMAGE="${EKKO_NGINX_IMAGE:-}"
HTTP_PORT="${EKKO_HTTP_PORT:-8080}"

usage() {
  cat >&2 <<EOF
Usage: sudo $0 [--stack-dir DIR] [--primary-url URL] [--environment NAME]
               [--security-key KEY] [--php-image REF] [--nginx-image REF]
               [--http-port N]
EOF
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --stack-dir) STACK_DIR="$2"; shift 2 ;;
    --primary-url) PRIMARY_URL="$2"; shift 2 ;;
    --environment) ENVIRONMENT="$2"; shift 2 ;;
    --security-key) SECURITY_KEY="$2"; shift 2 ;;
    --php-image) PHP_IMAGE="$2"; shift 2 ;;
    --nginx-image) NGINX_IMAGE="$2"; shift 2 ;;
    --http-port) HTTP_PORT="$2"; shift 2 ;;
    -h | --help) usage ;;
    *) echo "Unknown option: $1" >&2; usage ;;
  esac
done

if [[ "$(id -u)" -ne 0 ]]; then echo "Run as root (sudo)." >&2; exit 1; fi
[[ -z "${PRIMARY_URL}" ]] && { echo "--primary-url is required." >&2; exit 1; }
[[ -z "${PHP_IMAGE}"   ]] && { echo "--php-image is required."   >&2; exit 1; }
[[ -z "${NGINX_IMAGE}" ]] && { echo "--nginx-image is required." >&2; exit 1; }

if [[ ! -f /etc/ekko-craft.env ]]; then
  echo "Missing /etc/ekko-craft.env (Terraform VM startup did not run?)." >&2
  exit 1
fi

# shellcheck disable=SC1091
set -a; source /etc/ekko-craft.env; set +a

: "${EKKO_GCP_PROJECT:?}"
: "${EKKO_DB_SECRET_ID:?}"
: "${EKKO_DB_USER:?}"
: "${EKKO_DB_NAME:?}"
: "${EKKO_CLOUDSQL_CONNECTION:?}"

mkdir -p "${STACK_DIR}"

if [[ -z "${SECURITY_KEY}" && -f "${STACK_DIR}/.security-key" ]]; then
  SECURITY_KEY="$(cat "${STACK_DIR}/.security-key")"
fi
if [[ -z "${SECURITY_KEY}" ]]; then
  if command -v openssl >/dev/null 2>&1; then
    SECURITY_KEY="$(openssl rand -base64 48 | tr -d '\n')"
  else
    SECURITY_KEY="$(head -c 48 /dev/urandom | base64 | tr -d '\n')"
  fi
  umask 077
  printf '%s' "$SECURITY_KEY" >"${STACK_DIR}/.security-key"
  umask 022
fi

export WR_CMS_ENV_PATH="${STACK_DIR}/cms.env"
export WR_PRIMARY_URL="$PRIMARY_URL"
export WR_ENVIRONMENT="$ENVIRONMENT"
export WR_SECURITY_KEY="$SECURITY_KEY"
export WR_PROJECT="$EKKO_GCP_PROJECT"
export WR_SECRET_ID="$EKKO_DB_SECRET_ID"
export WR_DB_USER="$EKKO_DB_USER"
export WR_DB_NAME="$EKKO_DB_NAME"

python3 <<'PY'
import base64, json, os, pathlib, ssl, urllib.request, uuid

meta = "http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token"
req = urllib.request.Request(meta, headers={"Metadata-Flavor": "Google"})
with urllib.request.urlopen(req, timeout=30) as r:
    tok = json.loads(r.read().decode())["access_token"]

url = (
    "https://secretmanager.googleapis.com/v1/projects/"
    + os.environ["WR_PROJECT"]
    + "/secrets/"
    + os.environ["WR_SECRET_ID"]
    + "/versions/latest:access"
)
req = urllib.request.Request(url, headers={"Authorization": "Bearer " + tok})
with urllib.request.urlopen(req, context=ssl.create_default_context(), timeout=60) as r:
    body = json.loads(r.read().decode())
db_password = base64.b64decode(body["payload"]["data"]).decode()

def q(s): return json.dumps(s)

lines = [
    "# Generated by scripts/vm/write-cms-env.sh — do not edit by hand.",
    "",
    f"ENVIRONMENT={q(os.environ['WR_ENVIRONMENT'])}",
    f"APP_ID={q('CraftCMS--' + str(uuid.uuid4()))}",
    f"SECURITY_KEY={q(os.environ['WR_SECURITY_KEY'])}",
    "",
    'DB_DRIVER="mysql"',
    'DB_SERVER="cloudsql"',
    'DB_PORT="3306"',
    f"DB_DATABASE={q(os.environ['WR_DB_NAME'])}",
    f"DB_USER={q(os.environ['WR_DB_USER'])}",
    f"DB_PASSWORD={q(db_password)}",
    'DB_SCHEMA=""',
    'DB_TABLE_PREFIX="craft_"',
    "",
    f"SITE_URL={q(os.environ['WR_PRIMARY_URL'])}",
    "",
]

p = pathlib.Path(os.environ["WR_CMS_ENV_PATH"])
p.write_text("\n".join(lines) + "\n", encoding="utf-8")
p.chmod(0o640)
PY

# The php container runs as www-data (uid 33); let it read the mounted env.
chown root:33 "${STACK_DIR}/cms.env"
chmod 640 "${STACK_DIR}/cms.env"

umask 077
cat >"${STACK_DIR}/.env.gcp" <<EOF
# Generated by scripts/vm/write-cms-env.sh — compose env only, no secrets.
EKKO_PHP_IMAGE=${PHP_IMAGE}
EKKO_NGINX_IMAGE=${NGINX_IMAGE}
EKKO_CLOUDSQL_CONNECTION=${EKKO_CLOUDSQL_CONNECTION}
HTTP_PORT=${HTTP_PORT}
EOF
chmod 640 "${STACK_DIR}/.env.gcp"
umask 022

echo "Wrote ${STACK_DIR}/cms.env and ${STACK_DIR}/.env.gcp."
