handle: toggle
instructions: ''
maxNodes: ''
name: Toggle
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  custom:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
  verbb\navigation\nodetypes\SiteType:
    enabled: '1'
propagateNodes: false
siteSettings:
  2ca3c368-1b4f-48ad-b4a2-1aa79f9ce6af: # EKKO (en)
    enabled: '1'
  cc892d6a-abac-456e-83a9-260fd5616d45: # EKKO (nb)
    enabled: '1'
sortOrder: 6
structure:
  maxLevels: null
  uid: 7ce53207-12eb-4002-bc50-5a2a18d9ae74
