fieldLayouts:
  b83ea098-da62-4427-a2b2-f51c36b32838:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d7d0eb21-d78a-41ee-b04f-abf638456ebf
            warning: null
            width: 100
          -
            fieldUid: 55541fc5-e1a7-4cd6-abe4-3399885a9895 # Artist Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 647e9094-c217-4efc-b496-37084fd4ff0c
            warning: null
            width: 100
          -
            fieldUid: ffb359c7-60c8-490b-8731-0943d3dc9130 # Ekstra info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2026b2e-156c-4a37-8778-cb5e2f84c0b4
            warning: null
            width: 100
        name: Innhold
        sortOrder: 1
        uid: bf5472c0-06b0-4dcb-8464-33dcaa450608
fs: artistPhotos
handle: artistPhotos
hasUrls: true
name: 'Artist Photos'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
url: '@assetBaseUrl/photos/artists'
