fieldLayouts:
  91843676-81cd-462b-9434-cbd2ba994c8e:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 73a3251b-efc3-4e04-b5ce-b0fb09a1febd
            warning: null
            width: 100
          -
            fieldUid: 55541fc5-e1a7-4cd6-abe4-3399885a9895 # Artist Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11145c7a-a9f6-4116-88ff-0e10d6ebbf95
            warning: null
            width: 100
          -
            fieldUid: ffb359c7-60c8-490b-8731-0943d3dc9130 # Ekstra info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bb20821-53b7-4f29-a973-12e1cafa41f5
            warning: null
            width: 100
        name: Innhold
        sortOrder: 1
        uid: 49660f59-f672-4ff4-8afc-17b7a1ae131f
fs: eventPhoto
handle: eventPhoto
hasUrls: true
name: 'Event Photo'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
url: '@assetBaseUrl/photos/events'
