fieldLayouts:
  fbd60a6e-133e-422f-89f0-64973c65e1ee:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ee57549b-dcb5-43b7-bbae-af723dc092c1
            warning: null
            width: 100
        name: Innhold
        sortOrder: 1
        uid: fd495fe3-3681-40c2-a7c7-8f5e28cd5e73
fs: mixtapes
handle: mixtapes
hasUrls: true
name: Mixtapes
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: none
url: '@assetBaseUrl/mixtapes'
