fieldLayouts:
  aee623f5-9c73-4d0f-9949-7a48803282bc:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 42e30ec9-0742-4a9e-b8ed-ed0ab43136a6
            warning: null
            width: 100
        name: Content
        sortOrder: 1
        uid: a814ab61-da0c-43da-b132-d4e20bc1a288
fs: userPhotos
handle: userPhotos
hasUrls: false
name: 'User Photos'
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
url: null
