fieldLayouts:
  0a2a1b76-989b-4c9a-a480-707de9d34165:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: ae576b05-f687-4113-b558-1c2565b364c3
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: aac99d83-a88a-4a4b-b3fd-6c95266a5b49
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e870c8fc-0214-40e0-8ad6-7d0629c6a6dc
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dc8b8360-0719-4c2c-a380-700ba0fb559c
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a83084f4-78bc-49ff-b261-5a07cc42602f
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2ca9087d-6867-4b6b-9f29-096d9d6c0206
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b17e65dc-e435-41f3-89e9-2ec9c3b44284
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4f6b207f-e60c-4b99-aa84-78e8bc6dab2c
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Information (Program)'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: e615d2b1-f4e4-4e6b-895c-957eff051ea2
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Performances
        sortOrder: 2
      -
        elements:
          -
            fieldUid: df7b834e-e4f7-4ceb-ae3a-07aa0cd8ca9a
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 356f072d-7d91-4223-80eb-d842012888a3
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8c14763b-6183-46a0-be68-963de453e209
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Description
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 2fa144e3-9d6c-4375-aac7-25bff4a94612
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 501c383f-cb02-4039-973f-c098638b4b84
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Tickets
        sortOrder: 4
handle: event
hasTitleField: true
name: Event
section: 301645ea-e60b-4a0b-bb67-58f74bdbca11
sortOrder: 0
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
