defaultPlacement: end
enableVersioning: false
entryTypes:
  -
    uid: 86d6422d-170f-488a-9545-22f573b34683 # News entry
handle: news
maxAuthors: 1
name: News
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - Homepage
      -
        - urlFormat
        - '/#news'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2ca3c368-1b4f-48ad-b4a2-1aa79f9ce6af: # EKKO (en)
    enabledByDefault: true
    hasUrls: true
    template: news\_entry
    uriFormat: 'news/{slug}'
  cc892d6a-abac-456e-83a9-260fd5616d45: # EKKO (nb)
    enabledByDefault: true
    hasUrls: true
    template: news\_entry
    uriFormat: 'nyheter/{slug}'
type: channel
