field: c160fb14-bd1a-4690-9b04-2932d04eaca0 # Sections
fieldLayouts:
  bc93e8ba-f507-4ef5-92c3-8506e913dcb4:
    tabs:
      -
        elements:
          -
            fieldUid: fe7864fc-1423-4b7f-b731-3d69261b7765 # Section Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f63b15ea-6503-4137-9f87-96cc3152d0fd # Section Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e2bb1603-0d05-4682-9124-496596dec40e # Section ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d404b7fc-c59d-4cf6-97f8-2648cd4fd07c # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  d404b7fc-c59d-4cf6-97f8-2648cd4fd07c: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:51241002-1701-4f06-ae6e-59496b8a42a2' # Artist Photos
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:51241002-1701-4f06-ae6e-59496b8a42a2' # Artist Photos
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  e2bb1603-0d05-4682-9124-496596dec40e: # Section ID
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: sectionId
    instructions: "ID, that can be used to create the link in festival sub-navigation. To link to this section, use '#....' format.\r\nBy default, the value from Section Title is used."
    name: 'Section ID'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f63b15ea-6503-4137-9f87-96cc3152d0fd: # Section Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: sectionBody
    instructions: ''
    name: 'Section Body'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: ''
      redactorConfig: Normal.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  fe7864fc-1423-4b7f-b731-3d69261b7765: # Section Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: sectionTitle
    instructions: ''
    name: 'Section Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: entry
name: Entry
sortOrder: 1
