field: 7e6f5fa9-c7c3-4df8-b0f8-c98ee2362329 # Past events
fieldLayouts:
  77c534d4-4463-48f1-812c-bf89758303fd:
    tabs:
      -
        elements:
          -
            fieldUid: 735e30e0-3a6a-43dd-b34f-281cd6d87761 # Title
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eba0ecfa-bdbc-40c1-a6c7-0c553f1f2cfb # Is festival
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6db46c9d-527e-48d0-957a-3d79690d4d79 # Start date
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 748a4e8a-77d5-4e80-aabd-bf595e378994 # End date
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 457d2dfa-5bc9-453a-87c3-b20147d4ea1b # Artists
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6db46c9d-527e-48d0-957a-3d79690d4d79: # Start date
    columnSuffix: null
    contentColumnType: datetime
    fieldGroup: null
    handle: date
    instructions: ''
    name: 'Start date'
    searchable: true
    settings:
      max: null
      min: null
      minuteIncrement: '30'
      showDate: 1
      showTime: 0
      showTimeZone: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
  457d2dfa-5bc9-453a-87c3-b20147d4ea1b: # Artists
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: artists
    instructions: 'List artists each one on a separate line.'
    name: Artists
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  735e30e0-3a6a-43dd-b34f-281cd6d87761: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: eventTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  748a4e8a-77d5-4e80-aabd-bf595e378994: # End date
    columnSuffix: null
    contentColumnType: datetime
    fieldGroup: null
    handle: dateEnd
    instructions: ''
    name: 'End date'
    searchable: true
    settings:
      max: null
      min: null
      minuteIncrement: '30'
      showDate: 1
      showTime: 0
      showTimeZone: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
  eba0ecfa-bdbc-40c1-a6c7-0c553f1f2cfb: # Is festival
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: isFestival
    instructions: ''
    name: 'Is festival'
    searchable: true
    settings:
      default: true
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: event
name: Event
sortOrder: 1
