columnSuffix: null
contentColumnType: text
fieldGroup: 3626e6f0-4597-4098-b20a-fb662ff583a7 # Artist
handle: artistMeta
instructions: ''
name: 'Label / Land'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
