columnSuffix: null
handle: customTitle
instructions: null
name: 'Lineup - Lineup entry - Custom title'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: Lineup.json
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showHtmlButtonForNonAdmins: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
