columnSuffix: fxfbepdj
contentColumnType: boolean
handle: darkMode
instructions: 'Turn on page dark mode'
name: 'Dark mode'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
