columnSuffix: null
contentColumnType: datetime
handle: date
instructions: ''
name: Date
searchable: true
settings:
  max: null
  min: null
  minuteIncrement: '30'
  showDate: 1
  showTime: 0
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
