columnSuffix: null
handle: date2
instructions: null
name: 'Past events - Event - Start date'
searchable: true
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
