columnSuffix: null
handle: eventEntries
instructions: null
name: 'Page Structure - Events - Event entries'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Select event entries'
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedEntries: true
  showUnpermittedSections: true
  sources:
    - 'section:301645ea-e60b-4a0b-bb67-58f74bdbca11' # Events
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
