columnSuffix: null
contentColumnType: boolean
handle: festivalLinkInvert
instructions: 'Activate for white (default black)'
name: 'Link color'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
