columnSuffix: null
contentColumnType: text
handle: festivalSectionTitle
instructions: ''
name: 'Festival section title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
