columnSuffix: null
contentColumnType: string(7)
handle: festivalSectionTextColor
instructions: ''
name: 'Text color'
searchable: true
settings:
  defaultColor: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
