columnSuffix: null
contentColumnType: text
fieldGroup: 3a538f39-9d08-43bc-b64f-ca7ddbd1552b # Index
handle: festivalSectionSubtitle
instructions: ''
name: 'Festival section subtitle'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
