columnSuffix: hncpufth
contentColumnType: boolean
handle: isComplexContent
instructions: ''
name: 'Content type'
searchable: false
settings:
  default: false
  offLabel: Simple
  onLabel: Complex
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
