columnSuffix: null
contentColumnType: boolean
handle: isVisible
instructions: 'is the artist visible on various lists in the website?'
name: Visible
searchable: true
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
