columnSuffix: null
contentColumnType: string
fieldGroup: 3a538f39-9d08-43bc-b64f-ca7ddbd1552b # Index
handle: linkedFestival
instructions: ''
name: 'Linked festival'
searchable: true
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: 'Select festival'
  showSiteMenu: true
  source: null
  sources:
    - 'section:301645ea-e60b-4a0b-bb67-58f74bdbca11' # Events
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
