columnSuffix: null
contentColumnType: string
handle: linkedEvents
instructions: ''
name: 'Linked events'
searchable: true
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: 'Select events'
  showSiteMenu: true
  source: null
  sources:
    - 'section:301645ea-e60b-4a0b-bb67-58f74bdbca11' # Events
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
