columnSuffix: null
contentColumnType: text
fieldGroup: 9e233a7f-8f79-4de8-9450-ffd21b8baeb6 # News
handle: newsContent
instructions: ''
name: Content
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  cleanupHtml: '1'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: '1'
  redactorConfig: Normal.json
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showHtmlButtonForNonAdmins: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  uiMode: enlarged
translationKeyFormat: null
translationMethod: site
type: craft\redactor\Field
