columnSuffix: null
contentColumnType: text
fieldGroup: 9e233a7f-8f79-4de8-9450-ffd21b8baeb6 # News
handle: newsEmbed
instructions: ''
name: Embed
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
