columnSuffix: null
contentColumnType: string
handle: organizer
instructions: ''
name: Organizer
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: '1'
  limit: null
  localizeRelations: false
  selectionLabel: 'Select event organizer'
  showSiteMenu: false
  source: 'group:83dec1cb-a705-4029-9aaf-3ec28ce4a629' # Organizers
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
