columnSuffix: null
contentColumnType: text
fieldGroup: eb356161-6f1c-45f0-a453-18af378140dd # Page
handle: pageTitle
instructions: ''
name: Title
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
