columnSuffix: null
contentColumnType: string
fieldGroup: 1a9347e1-e75c-4664-982f-4cf62da8d14f # Default
handle: pastEvents
instructions: ''
name: 'Past events'
searchable: true
settings:
  contentTable: '{{%matrixcontent_pastevents}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
