columnSuffix: null
contentColumnType: string
handle: pastEvents
instructions: ''
name: 'Past events'
searchable: true
settings:
  entryTypes:
    -
      handle: event
      uid: 203b3f7a-11d6-44e4-b95e-db08891146dd
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
