columnSuffix: null
contentColumnType: string
handle: program
instructions: ''
name: Program
searchable: true
settings:
  entryTypes:
    -
      uid: 65bbb9d7-e875-4863-9465-da3909239e2e
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
