columnSuffix: null
contentColumnType: string
handle: relatedLinks
instructions: ''
name: 'Related links'
searchable: true
settings:
  entryTypes:
    -
      uid: 196718d0-fc92-43e0-a523-8b970b98601d
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: none
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
