columnSuffix: ynqltqgf
contentColumnType: text
fieldGroup: 7f4be85f-cd38-42ea-afed-25ab3fd2648e # Globals
handle: room
instructions: ''
name: Room
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
