columnSuffix: null
contentColumnType: string
fieldGroup: 2b5f0159-6c20-4857-9ad4-bd686b1e3ce8 # Event
handle: sections
instructions: ''
name: Sections
searchable: true
settings:
  contentTable: '{{%matrixcontent_sections}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
