columnSuffix: null
handle: sectionBody
instructions: null
name: 'Sections - Entry - Section Body'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: false
  redactorConfig: Normal.json
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showHtmlButtonForNonAdmins: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  uiMode: enlarged
translationKeyFormat: null
translationMethod: site
type: craft\redactor\Field
