columnSuffix: null
handle: sectionTitle
instructions: null
name: 'Page Structure - Events - Event section title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Andre prosjekter'
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
