columnSuffix: null
contentColumnType: string
handle: sections
instructions: ''
name: Sections
searchable: true
settings:
  entryTypes:
    -
      uid: da23ad02-2442-4045-aab6-73b590eb5bbf
  maxEntries: ''
  minEntries: ''
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
