columnSuffix: null
contentColumnType: boolean
fieldGroup: 2b5f0159-6c20-4857-9ad4-bd686b1e3ce8 # Event
handle: showArtistInfo
instructions: 'If selected, artist info will be shown on event page'
name: 'Show Artist Info'
searchable: false
settings:
  default: true
  offLabel: Hide
  onLabel: Show
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
