columnSuffix: null
contentColumnType: boolean
handle: showArtistInfo
instructions: 'If selected, artist info will be shown on event page'
name: 'Show Artist Info'
searchable: false
settings:
  default: true
  offLabel: Hide
  onLabel: Show
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
