columnSuffix: null
contentColumnType: boolean
handle: singlePage
instructions: 'If single page is selected, there is no need for artist pages or event image and you can use the intro field to describe the artists.'
name: 'Single Page'
searchable: false
settings:
  default: true
  offLabel: 'Multiple Page'
  onLabel: 'Single Page'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
