columnSuffix: null
contentColumnType: string
handle: stampAlternative
instructions: 'Stamp image, that will be visible in mobile layouts inside a colored box. Stamp color usually should be light.'
name: 'Festival stamp - mobile'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:51241002-1701-4f06-ae6e-59496b8a42a2' # Artist Photos
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:51241002-1701-4f06-ae6e-59496b8a42a2' # Artist Photos
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:9654b4af-cff4-49e6-b9b3-a3071afc2549' # Event Photo
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
