columnSuffix: null
contentColumnType: text
handle: ticketFrame
instructions: 'TicketCo ticket iFrame template with the <ID> placeholder.'
name: 'Ticket Frame Code'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
