columnSuffix: null
contentColumnType: datetime
handle: timeEnd
instructions: ''
name: 'End Time'
searchable: true
settings:
  max: null
  min: null
  minuteIncrement: '15'
  showDate: 0
  showTime: 1
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
