columnSuffix: null
handle: videoUrl2
instructions: 'Full youtube or vimeo video URL.'
name: 'Content - Video block - Video URL'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
