enableVersioning: true
handle: artists
name: Artists
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  2ca3c368-1b4f-48ad-b4a2-1aa79f9ce6af:
    enabledByDefault: true
    hasUrls: true
    template: artists/_entry
    uriFormat: 'artists/{slug}'
  cc892d6a-abac-456e-83a9-260fd5616d45:
    enabledByDefault: true
    hasUrls: true
    template: artists/_entry
    uriFormat: 'artists/{slug}'
structure:
  maxLevels: 1
  uid: f40dd886-0540-4363-bdef-7d070122aa2f
type: structure
