fieldLayouts:
  b138f812-51bf-40e6-8a8a-6651ed8e049e:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d1a8cbe6-6b59-4dac-9984-8147889fb3b1
            warning: null
            width: 100
          -
            fieldUid: 248a979b-096c-45c3-a339-2a663262c6da # Title
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08303a69-0bc4-4b00-978f-0eaa1e0f4c1c
            warning: null
            width: 100
          -
            fieldUid: c869bdc9-08cf-4e74-bcc8-ad30e1d3fe41 # Content
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5517d502-b043-4c07-8422-9b521c31e87d
            warning: null
            width: 100
          -
            fieldUid: 7e6f5fa9-c7c3-4df8-b0f8-c98ee2362329 # Past events
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0db5ed09-3a99-42e9-8211-db950e74ccf8
            warning: null
            width: 100
        name: Content
        sortOrder: 1
        uid: b9422179-2573-4a74-b20e-952ec074814f
handle: archive
hasTitleField: false
name: Archive
sortOrder: 0
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
