fieldLayouts:
  f8521b62-3a63-498b-bd0c-e7c5b1661ea9:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b3b8f4ce-7793-43eb-a404-cef90b808504
            warning: null
            width: 100
          -
            fieldUid: 55541fc5-e1a7-4cd6-abe4-3399885a9895 # Artist Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1df94c10-0a8e-4728-b1b2-315f5bf9d2ea
            warning: null
            width: 100
          -
            fieldUid: 925eb546-1db1-441b-9eda-02e8a14087d8 # Project Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0f7412d-7f4b-4bbf-abc7-4dd80d74c69c
            warning: null
            width: 100
          -
            fieldUid: e9334691-89a8-4b92-b749-c1828f91bcdc # Project Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db2455ff-cd59-403e-a80e-f18094953d4b
            warning: null
            width: 100
          -
            fieldUid: c869bdc9-08cf-4e74-bcc8-ad30e1d3fe41 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4edf68c1-1112-442d-8156-4e84fe119e83
            warning: null
            width: 100
          -
            fieldUid: ee855f1b-d9fe-4b11-a96b-0016a8583550 # Video
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c83c7e1e-4fbd-41c4-8718-1b98167ea46d
            warning: null
            width: 100
          -
            fieldUid: 59128b6e-6a78-4cb2-b45d-de838ae65db7 # Artist
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d1281f2-4333-4b27-9f19-8094b1b7858f
            warning: null
            width: 100
          -
            fieldUid: e615d2b1-f4e4-4e6b-895c-957eff051ea2 # Performances
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3f0a5ff-6831-4e7b-854e-152c7d48366e
            warning: null
            width: 100
        name: Content
        sortOrder: 1
        uid: ca199276-3850-4414-9f05-761852e5264f
handle: arenaVideo
hasTitleField: true
name: 'Video Project'
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
