fieldLayouts:
  7963c823-2baf-4cdb-8529-d1a7310b8502:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 751eabed-1d00-4858-bda9-c363f90e55ca
            warning: null
            width: 100
          -
            fieldUid: fa5a5a49-846d-41cc-901c-df6a21381707 # Label / Land
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9f3fac5-34e7-4d8a-bf80-43194e64c149
            warning: null
            width: 100
          -
            fieldUid: ea002f54-0097-486c-92bd-64c3b9e6a624 # Featured Photo
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f918bf10-e789-4492-a5c4-a0b9a919d850
            warning: null
            width: 100
          -
            fieldUid: b1f43e32-e00a-4259-837c-60b67111e847 # Content
            instructions: 'General information about artist, his biography.'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f255b01-11db-46bd-b5e0-f7266c8ae275
            warning: null
            width: 100
          -
            fieldUid: e80f79d5-8bfd-403b-8703-cd18785dc47c # Related links
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5623187-f3cb-48ad-98e5-b46f537dcea1
            warning: null
            width: 100
        name: Information
        sortOrder: 1
        uid: d8abad45-5615-42d8-b2b4-65a2fa4db5b0
      -
        elements:
          -
            fieldUid: ba09eebe-08ba-452b-8ac2-62c7819a9d1c # Short Title
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5654eac8-1d69-4d60-abaa-8fab35547927
            warning: null
            width: 100
          -
            fieldUid: 35b5fed5-df63-47d2-b504-053234e39c77 # Featured
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 805ee0ab-15ca-48f6-aedf-73929737faf2
            warning: null
            width: 100
          -
            fieldUid: 5fc61e39-3eae-450e-8b99-8afe110e9a1c # Visible
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02ddaac5-e075-41f1-9d04-dde9e1501cab
            warning: null
            width: 100
          -
            fieldUid: 8140a09c-ef4e-4a14-8baa-91c6a5717ade # Hide "read more"
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a54740ca-c6bf-4beb-9253-fa79dbfd969e
            warning: null
            width: 100
        name: 'Old Fields'
        sortOrder: 2
        uid: 0f5f7c6c-c460-42ae-b995-c90c0e26f7d8
handle: artist
hasTitleField: true
name: Artist
sortOrder: 0
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
