fieldLayouts:
  fca3c52e-6f5a-4182-86bc-584dd9300aa3:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f0eabcf0-13ce-42bf-9d08-89573281c885
            warning: null
            width: 100
          -
            fieldUid: 248a979b-096c-45c3-a339-2a663262c6da # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10a8a952-18b6-41ba-a2ce-ca42a6ee4d8a
            warning: null
            width: 100
          -
            fieldUid: 15991c6c-d005-4d63-9da7-e6cb34ba408d # Contact
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47ca7810-e915-4461-af4b-d62b60442eeb
            warning: null
            width: 100
          -
            fieldUid: c869bdc9-08cf-4e74-bcc8-ad30e1d3fe41 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ec5ee75-da95-40b5-aaae-c7948cbc5a8b
            warning: null
            width: 100
          -
            fieldUid: 06b58602-3190-496b-95cc-833c4c279b62 # Linked festival
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 916a84c8-4b5a-4722-be60-ba8b236b0388
            warning: null
            width: 100
        name: Content
        sortOrder: 1
        uid: e26f276d-f0b9-45b9-8fb5-1e9c19a231fd
      -
        elements:
          -
            fieldUid: 0f8e83d0-47dc-4eeb-89ba-c2ec7db13cc1 # Gallery
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: accdc18f-7acd-4077-9dcf-cc20fc211c8f
            warning: null
            width: 100
        name: Gallery
        sortOrder: 2
        uid: 5d157e22-cc6e-4ccc-9cb2-9a28acd039d1
handle: ekko_festival_info
hasTitleField: false
name: 'Ekko Festival'
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
