fieldLayouts:
  f8739ad9-0c1f-4226-b509-bcbd25839042:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: ba09eebe-08ba-452b-8ac2-62c7819a9d1c # Short Title
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fa5a5a49-846d-41cc-901c-df6a21381707 # Label / Land
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 35b5fed5-df63-47d2-b504-053234e39c77 # Featured
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5fc61e39-3eae-450e-8b99-8afe110e9a1c # Visible
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ea002f54-0097-486c-92bd-64c3b9e6a624 # Featured Photo
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fa00f016-59a7-4fd1-92ee-f346c3ab6d63 # Opening Times
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b1f43e32-e00a-4259-837c-60b67111e847 # Content
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Information
        sortOrder: 1
handle: exhibition
hasTitleField: true
name: Exhibition
section: 55ac0cf8-926f-4ebf-beda-5e9defe5c90b # Artists
sortOrder: 0
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
