fieldLayouts:
  b96be739-737d-4df8-953c-7d8e6c296078:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0d0ab3e0-1a5d-4a9e-aaed-ecdc3dad7a29
            warning: null
            width: 100
          -
            fieldUid: 248a979b-096c-45c3-a339-2a663262c6da # Title
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a57c7126-b6ae-479e-af0e-2afa15a20a51
            warning: null
            width: 100
          -
            fieldUid: 187397bc-8c24-4472-80eb-d89d2511e444 # Cover photo
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73979daf-449f-4219-b182-9d671dd4e045
            warning: null
            width: 100
          -
            fieldUid: c869bdc9-08cf-4e74-bcc8-ad30e1d3fe41 # Content
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a93c856c-8076-481c-a2d6-9909b2504630
            warning: null
            width: 100
        name: Content
        sortOrder: 1
        uid: 5be81409-6b9b-411b-bc37-73cfaa5cc25f
handle: legal
hasTitleField: false
name: Legal
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
