allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  f939e842-4d11-4c43-9932-1725df5f3440:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:bf4e962a-9212-41e6-9bb4-24bd87ebe355'
      - 'layoutElement:aef1eb27-2c1e-429d-9eaf-42943e71c775'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1ece1b63-6a8c-4ff9-8508-9d49f2215a06
            handle: null
            instructions: null
            label: 'Link title'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf4e962a-9212-41e6-9bb4-24bd87ebe355
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c1095f5c-a9ea-4d2e-a9df-89ba5530d3d7
            handle: null
            instructions: null
            label: 'Link url'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aef1eb27-2c1e-429d-9eaf-42943e71c775
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4911ded4-4197-432a-b823-1989d73b9d97
        userCondition: null
    thumbFieldKey: null
handle: link
hasTitleField: false
icon: null
name: Link
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
