fieldLayouts:
  254dd3a0-3cfb-403c-b120-ca8296f1141c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 7fc19e46-47b3-4539-803a-471f5f202b63 # Intro
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b1f43e32-e00a-4259-837c-60b67111e847 # Content
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 187397bc-8c24-4472-80eb-d89d2511e444 # Cover photo
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: 'Frontpage media'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 945a4d5e-8361-4e0b-8255-aecb12ef406c # Photo
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bf7ac7e8-a3a9-4cd4-b20b-1dc0622dbe46 # Embed
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 68d30209-da86-48e0-ae80-48d9873ef92e # Media position
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Media
        sortOrder: 2
      -
        elements:
          -
            style: warning
            tip: 'Following fields are not used anymore in the webpage. Fields are left available if editors would still need to use the content  in new fields when migrating old entries.'
            type: craft\fieldlayoutelements\Tip
          -
            fieldUid: 23e69913-2e5b-412f-a67f-946af1b360e8 # Content
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Deprecated Fields'
        sortOrder: 3
handle: newsEntry
hasTitleField: true
name: 'News entry'
section: 0e779b2c-f6e5-4cc0-a81c-53479e1587de # News
sortOrder: 0
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
