dateModified: 1776937359
email:
  fromEmail: pasidejau@gmail.com
  fromName: EKKO
  template: null
  transportType: craft\mail\transportadapters\Sendmail
fs:
  artistPhotos:
    hasUrls: true
    name: 'Artist Photos'
    settings:
      path: '@assetBasePath/photos/artists'
    type: craft\fs\Local
    url: '@assetBaseUrl/photos/artists'
  eventPhoto:
    hasUrls: true
    name: 'Event Photo'
    settings:
      path: '@assetBasePath/photos/events'
    type: craft\fs\Local
    url: '@assetBaseUrl/photos/events'
  mixtapes:
    hasUrls: true
    name: Mixtapes
    settings:
      path: '@assetBasePath/mixtapes'
    type: craft\fs\Local
    url: '@assetBaseUrl/mixtapes'
  userPhotos:
    hasUrls: false
    name: 'User Photos'
    settings:
      path: '@storage/userphotos'
    type: craft\fs\Local
    url: null
meta:
  __names__:
    000db67a-24a2-4bcf-9791-76def17c6393: 'Page Structure' # Page Structure
    00e171fa-0c13-4b5c-8027-de814c0b61db: Organizer # Organizer
    0e779b2c-f6e5-4cc0-a81c-53479e1587de: News # News
    0ed83704-dc8c-4a51-8ef6-4d9805b65f55: 'Single Page' # Single Page
    0f8e83d0-47dc-4eeb-89ba-c2ec7db13cc1: Gallery # Gallery
    1a637861-ca68-4b37-89b2-4749e2df9e77: 'New Navigation' # New Navigation
    2abbde3f-ca06-4440-8377-78cca305429c: 'Background color' # Background color
    2ca3c368-1b4f-48ad-b4a2-1aa79f9ce6af: 'EKKO (en)' # EKKO (en)
    2ca9087d-6867-4b6b-9f29-096d9d6c0206: Location # Location
    2fa144e3-9d6c-4375-aac7-25bff4a94612: 'Ticket Description' # Ticket Description
    3ed993e6-828f-4ad3-9a3a-8b89d019607d: Østre # Østre
    04ad8bc5-41ba-46fc-83ee-9e939a4af8d4: 'Menu item entry' # Menu item entry
    4eb54b91-847f-49d3-85af-6fd97c2661b0: 'Festival Section content' # Festival Section content
    4f6b207f-e60c-4b99-aa84-78e8bc6dab2c: Layout # Layout
    5aeb8e69-596a-403d-970a-3a5f856e172a: 'Main Menu' # Main Menu
    5bb4803b-6adc-4b0c-8ee3-1fe72c59b1d7: Artist # Artist
    5fc61e39-3eae-450e-8b99-8afe110e9a1c: Visible # Visible
    6b9c6d34-b4f1-4d0b-8d3f-f93f629303a5: 'Parsed date & time' # Parsed date & time
    06b58602-3190-496b-95cc-833c4c279b62: 'Linked festival' # Linked festival
    6c52e813-75ce-4e21-8627-ca4024b4a3a0: Homepage # Homepage
    7aadc7b7-db7e-456a-8789-8acb1a6cb1cc: 'Thumb (large)' # Thumb (large)
    7c642643-8c47-4e38-a92e-1bc2a7de962f: 'Ekko Festival' # Ekko Festival
    7e6f5fa9-c7c3-4df8-b0f8-c98ee2362329: 'Past events' # Past events
    7fc19e46-47b3-4539-803a-471f5f202b63: Intro # Intro
    8b4e04f9-7e76-44b6-8cc3-5d146d8d62b5: Performance # Performance
    8c744ecf-5dca-4295-891d-f986a1167efb: Legal # Legal
    8c14763b-6183-46a0-be68-963de453e209: Description # Description
    9bd651ab-6fac-4a9c-bc60-505c61c7d8e0: Østre # Østre
    9cfd44dd-f0b0-43c0-a6fc-47a984ca0317: Default # Default
    9dd4983f-8b2b-45f7-937d-33fe34967949: 'Festival background color' # Festival background color
    20aece2a-ee02-4c26-b0ad-5006ad525667: Instagram # Instagram
    020f48a4-f969-42b4-b017-ff9c94cac7be: 'Ekko Festival' # Ekko Festival
    23e69913-2e5b-412f-a67f-946af1b360e8: Content # Content
    35a14bab-1bcf-4bd9-aacb-386c79147a44: 'Festival link text' # Festival link text
    35b5fed5-df63-47d2-b504-053234e39c77: Featured # Featured
    38e3689e-6c07-47c2-af7f-406ac6e25708: 'Graphic element' # Graphic element
    41a34b95-1505-4c00-b475-992edeec3dd3: 'Menu item title' # Menu item title
    43bffe17-465b-4ef5-8557-5a5185b24e12: Østre # Østre
    047e1d05-f938-4535-beaa-42660f62eca7: 'Ekko site' # Ekko site
    54f6a4ae-b35f-48e8-8bed-2be391f3e8d9: 'Festival stamp - mobile' # Festival stamp - mobile
    55ac0cf8-926f-4ebf-beda-5e9defe5c90b: Artists # Artists
    55e2f47a-a791-4b6a-8cc3-d918e1342073: 'Global Information' # Global Information
    62db04ec-3204-4ab4-8ecc-ef980ab2e2e2: Program # Program
    62f3b664-9574-457c-a7fd-83e88255a397: Stamp # Stamp
    68d30209-da86-48e0-ae80-48d9873ef92e: 'Media position' # Media position
    71ff9901-9c95-4883-b9f2-27282e6584d5: About # About
    77eeaf4a-a76a-4b31-992b-a91edf496610: Homepage # Homepage
    77fadfa1-64d4-4d65-9f1b-d96ecdfdf404: 'Text color' # Text color
    83dec1cb-a705-4029-9aaf-3ec28ce4a629: Organizers # Organizers
    86d6422d-170f-488a-9545-22f573b34683: 'News entry' # News entry
    92d9f6e4-d8a9-4c6f-90b2-d79ee4de3fc8: Lineup # Lineup
    162b2b00-4439-4618-8365-b40dab8bcaf8: Toggle # Toggle
    196bdedc-ec5d-4598-9494-bd83c64bec41: Archive # Archive
    248a979b-096c-45c3-a339-2a663262c6da: Title # Title
    356f072d-7d91-4223-80eb-d842012888a3: Intro # Intro
    496d2b10-36b1-43fb-b114-c61c558b9c57: 'Full Title' # Full Title
    501c383f-cb02-4039-973f-c098638b4b84: 'Ticket Link' # Ticket Link
    569cc5f7-c3c6-4624-9070-cd060ecff171: 'Newsletter disclaimer' # Newsletter disclaimer
    606fc8b3-0d9d-4d91-b67a-de0a63d95f28: 'Ticket Frame Code' # Ticket Frame Code
    618b9f1d-5720-4c34-a4b0-b5e0caedf06a: Tickets # Tickets
    744a5e0e-c714-4887-88b3-31071a9077da: 'End Time' # End Time
    755c585f-b811-47dc-b91f-aed945420029: Event # Event
    847ba39f-d84e-4d90-8962-dd31e5a0fc85: Performance # Performance
    897a6dab-8ede-4c25-8a93-b0e5f5d6abf6: 'Section description (events)' # Section description (events)
    925eb546-1db1-441b-9eda-02e8a14087d8: 'Project Title' # Project Title
    932d182b-57a0-4ee3-9d96-a6693aa55436: Optimised # Optimised
    945a4d5e-8361-4e0b-8255-aecb12ef406c: Photo # Photo
    989baf15-ee1a-40bd-8587-4ac2033dba46: 'Foreningen Ekko' # Foreningen Ekko
    2636d2bc-c59f-4520-add8-6b673aeaf88a: 'Ekko Festival' # Ekko Festival
    4359dca9-1b0a-4ea5-8fd1-3aaa64ce2756: 'Festival section title' # Festival section title
    5238bc75-3c4c-488c-a7be-973e480d98e0: 'Digital Arena' # Digital Arena
    5350a5b0-cd1c-4419-b50a-4cd42eb769a7: Mixtapes # Mixtapes
    6092fc1e-80cc-4982-bbb9-ba9861cdcef3: Archive # Archive
    6975aa00-c9bf-4c06-92a7-51ca3e4df18d: 'Thumb (medium)' # Thumb (medium)
    7558bbac-b043-4d73-a6ae-be776de1486f: 'Festival section subtitle' # Festival section subtitle
    8140a09c-ef4e-4a14-8baa-91c6a5717ade: 'Hide "read more"' # Hide "read more"
    9654b4af-cff4-49e6-b9b3-a3071afc2549: 'Event Photo' # Event Photo
    15991c6c-d005-4d63-9da7-e6cb34ba408d: Contact # Contact
    39520ae1-2ccd-47c3-af18-ef1fd52c7098: 'Show Artist Info' # Show Artist Info
    51563ce2-dabd-46db-a7bf-21dbb70fced0: 'Main navigation' # Main navigation
    55541fc5-e1a7-4cd6-abe4-3399885a9895: 'Artist Name' # Artist Name
    56271c8c-5fe9-413c-bcb0-4c1e876ffe55: Time # Time
    59128b6e-6a78-4cb2-b45d-de838ae65db7: Artist # Artist
    69085be0-360e-4318-a157-d38cf06146c7: Test # Test
    187397bc-8c24-4472-80eb-d89d2511e444: 'Cover photo' # Cover photo
    301645ea-e60b-4a0b-bb67-58f74bdbca11: Events # Events
    634406b0-0ba6-49ff-81ec-9267f0151462: 'Content type' # Content type
    822157ba-1ba2-424b-974b-5407629ba433: Lineup # Lineup
    5970721f-cec8-40e7-af75-ae37f9d9ee20: Legal # Legal
    51241002-1701-4f06-ae6e-59496b8a42a2: 'Artist Photos' # Artist Photos
    64644874-c3eb-45b1-bef6-5d51b056c516: Facebook # Facebook
    94498677-f4d1-4cc5-8215-47f4374daa28: 'Public Schema' # Public Schema
    a2b3d641-b542-4391-a1f7-26d081db16c6: Twitter # Twitter
    a24b012b-7bc1-487e-9244-96fcc5574445: 'Ticket modal content' # Ticket modal content
    a83084f4-78bc-49ff-b261-5a07cc42602f: 'Closing Time' # Closing Time
    aac99d83-a88a-4a4b-b3fd-6c95266a5b49: Date # Date
    ab8d9801-10ec-48fd-82bc-044e20cc18c4: linkedNews # linkedNews
    ab43f8e1-da4b-41d0-8169-b3282ace6aac: Room # Room
    abe8379b-6ad7-4679-9263-7962043daa0b: Festival # Festival
    ae576b05-f687-4113-b558-1c2565b364c3: 'Multiple Day Event' # Multiple Day Event
    af0f5492-b25f-45be-93c3-5925cce7ebcf: 'Section title (events)' # Section title (events)
    b1f43e32-e00a-4259-837c-60b67111e847: Content # Content
    b85882d9-26fb-4d9a-bd5d-6dce69ed358e: Locations # Locations
    b8829325-5023-46d1-b8a7-03d6dc33525b: Description # Description
    ba09eebe-08ba-452b-8ac2-62c7819a9d1c: 'Short Title' # Short Title
    bcef1f94-457a-4ebe-8250-016d2af30d83: 'Digital Arena Projects' # Digital Arena Projects
    bf7ac7e8-a3a9-4cd4-b20b-1dc0622dbe46: Embed # Embed
    bfad235c-53cd-431f-b5d9-b21b16c7dca3: 'Linked events' # Linked events
    c8b7ff51-a81c-4b49-a381-8c8021719cc2: 'User Photos' # User Photos
    c59fbaac-b3c9-4fa8-9884-60514bdfce35: 'Festival stamp' # Festival stamp
    c160fb14-bd1a-4690-9b04-2932d04eaca0: Sections # Sections
    c497f883-d2d9-46aa-9d6d-50f91ed90ba3: 'Menu item url' # Menu item url
    c869bdc9-08cf-4e74-bcc8-ad30e1d3fe41: Content # Content
    c395390c-ba83-4123-9a98-b48fd5ce35a1: 'Dark mode' # Dark mode
    cc892d6a-abac-456e-83a9-260fd5616d45: 'EKKO (nb)' # EKKO (nb)
    cd909105-de3f-40cc-bcef-3dcc79779872: Exhibition # Exhibition
    cea9678d-c4e5-419e-a431-1a0732fa9128: Venue # Venue
    d0a658ce-92a8-44f0-a55d-8b2e49b51d7e: About # About
    d81dc4d7-3875-487c-b4dd-a5a86aeef6c3: 'Newsletter modal content' # Newsletter modal content
    d7896b02-ef89-4b2d-bed9-2a1687ddaaa7: 'Enable link to festival entry' # Enable link to festival entry
    dc8b8360-0719-4c2c-a380-700ba0fb559c: 'Opening Time' # Opening Time
    df7b834e-e4f7-4ceb-ae3a-07aa0cd8ca9a: 'Featured Photo' # Featured Photo
    e80f79d5-8bfd-403b-8703-cd18785dc47c: 'Related links' # Related links
    e571f378-cb91-4304-a1b3-cb86027dec63: 'Link color' # Link color
    e615d2b1-f4e4-4e6b-895c-957eff051ea2: Performances # Performances
    e674f566-c3ed-48a7-abce-f4d4ca06d3d2: 'Video Project' # Video Project
    e870c8fc-0214-40e0-8ad6-7d0629c6a6dc: 'End Date' # End Date
    e9334691-89a8-4b92-b749-c1828f91bcdc: 'Project Tag' # Project Tag
    ea002f54-0097-486c-92bd-64c3b9e6a624: 'Featured Photo' # Featured Photo
    ebe72525-8597-4100-a8ba-480515957823: Østre # Østre
    ee855f1b-d9fe-4b11-a96b-0016a8583550: Video # Video
    f84c68dd-7976-4d13-9e29-b5f0a95b7320: EKKO # EKKO
    f789998e-fb56-4d6e-b00b-f3bdb902595a: 'Global Content' # Global Content
    fa00f016-59a7-4fd1-92ee-f346c3ab6d63: 'Opening Times' # Opening Times
    fa5a5a49-846d-41cc-901c-df6a21381707: 'Label / Land' # Label / Land
    ffb359c7-60c8-490b-8731-0943d3dc9130: 'Ekstra info' # Ekstra info
plugins:
  am-nav:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.7.4
    settings:
      canDoActions: ''
      pluginName: Navigasjon
      quietErrors: ''
  asset-rev:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-sort-cols:
    enabled: '1'
    licenseKey: null
    schemaVersion: '1.0'
    settings: null
  ekko:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  embedder:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  focal-point-field:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  hacksaw:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  imager:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  imager-x:
    edition: lite
    enabled: true
    licenseKey: OPG3EEV4QPEEEQRNJKP9IQQE
    schemaVersion: 4.0.0
  kint:
    enabled: '0'
    licenseKey: null
    schemaVersion: 1.0.0
    settings:
      kintDisplayTheme: aante-light
  mailchimp-subscribe:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.0.0
    settings:
      mcsubApikey: ''
      mcsubDoubleOptIn: '1'
      mcsubListId: 4512f2003b
  mix:
    enabled: '1'
    licenseKey: null
    schemaVersion: 0.1.0
    settings: null
  navigation:
    edition: standard
    enabled: true
    licenseKey: IQYN2X1GDL0K976TE35AFR82
    schemaVersion: 2.1.2
  preparse-field:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.1.0
    settings: null
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  site-switcher:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0
  spectrum:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  super-sort:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  supersort:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: EKKO
  retryDuration: null
  schemaVersion: 5.9.0.8
  timeZone: Europe/Oslo
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
